#ifndef _MAIN_MENU_CONSTANTS_HEADER_

#define _MAIN_MENU_CONSTANTS_HEADER_

enum MAIN_MENU_OPTIONS
{
    NONE_MAIN_MENU_OPTION = -1,
    NEW_GAME,
    LOAD_GAME,
    QUIT_GAME,
    RACE_CREATE_CHARACTER,
    CLASS_CREATE_CHARACTER,
    START_NEW_GAME,
    RETURN_CREATE_CHARACTER,
    START_LOADED_GAME,
};


#endif