#ifndef _FIGHT_CONSTANTS_HEADER 

#define _FIGHT_CONSTANTS_HEADER 

#define FIGHT_FUNCTION_INT_ERROR -1
#define FIGHT_FUNCTION_FLOAT_ERROR -1.0

enum FIGHT_CHARACTER_STATUS
{
    CHARACTER_IS_ALIVE = 0,
    CHARACTER_IS_DEAD,
    CHARACTER_KILLED_MONSTERS,
};

#endif